#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

monitor -d 1 2 3 4 5 6

config window_gap           8

config split_ratio                  0.50
config borderless_monocle true
config gapless_monocle true

rm $HOME/.cache/dunst.log

dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

picom --config ~/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
hsetroot -fill "$HOME/Pictures/Wallpapers/Reina.jpg"

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset m 0 0
