#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config window_gap           12

bspc config split_ratio                  0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_width 0

bspc config active_border_color "#928374"
bspc config normal_border_color "#665C54"

rm $HOME/.cache/dunst.log
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

picom --config ~/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
hsetroot -fill "$HOME/Pictures/Wallpapers/Yukiyui.jpg"

~/.config/polybar/launch.sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset m 0 0 &
